version: "3"
services:
  sample-mysql:
    image : mysql:8-debian
    container_name: sample-mysql
    ports:
      - "3306:3306"
    volumes:
      # dbのデータをlocalに保存する
      - ./db/mysql:/var/lib/mysql
      - ./config.cnf:/etc/mysql/conf.d/config.cnf
      - ./init-dump:/docker-entrypoint-initdb.d
      - ./:/app/src
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    working_dir: /app/src
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      application:
        ipv4_address: 172.30.0.2
networks:
  application:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
